test:
	g++ -std=c++14 -fopenmp TestCoreSetting.cpp -o test
parallel: seqalign_parallel2.cpp
	g++ -std=c++14 -fopenmp seqalign_parallel4.cpp -o parallel4
seq:
	g++ -std=c++14 -fopenmp seqalign.cpp -o seq
