test:
	g++ -std=c++14 -fopenmp TestCoreSetting.cpp -o test
parallel: seqalign_parallel2.cpp
	g++ -std=c++14 -fopenmp seqalign_parallel10.cpp -o parallel10
seq:
	g++ -std=c++14 -fopenmp seqalign.cpp -o seq
