test:
	g++ -std=c++14 -fopenmp TestCoreSetting.cpp -o test
parallel: seqalign_parallel2.cpp
	g++ -std=c++14 -fopenmp seqalign_parallel2.cpp -o parallel2
seq:
	g++ -std=c++14 -fopenmp seqalign.cpp -o seq
